manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk-config
      remote: zmkfirmware
      revision: main
      import: config/west.yml
  self:
    path: config
